"""Build dataset2/ YOLO structure from raw photos and custom annotations.

Steps performed:
	* Use 32 annotated images inside pic_annt/ as the training split.
	* Copy their JPEGs from raw/pictures/ and place YOLO label files alongside.
	* Reuse those annotated images for validation as well.
	* Treat remaining photos as background-only validation samples with empty labels.
	* Regenerate dataset2/ directory and dataset2.yaml.

Run from project root:
	uv run python utils/form_dataset2.py
"""

from __future__ import annotations

import os
from pathlib import Path
import shutil
from typing import List

LABELS_FILE = Path("labels.txt")
RAW_IMAGES_DIR = Path("raw/pictures")
ANNOTATIONS_DIR = Path("pic_annt")
OUTPUT_ROOT = Path("dataset2")
DATASET_YAML = Path("dataset2.yaml")


def load_class_names(labels_file: Path) -> List[str]:
	if not labels_file.exists():
		raise FileNotFoundError(f"Missing labels file: {labels_file}")
	with labels_file.open("r", encoding="utf-8") as fh:
		return [line.strip() for line in fh if line.strip()]


def parse_annotation(path: Path) -> List[str]:
	with path.open("r", encoding="utf-8") as fh:
		lines = [ln.strip() for ln in fh if ln.strip()]
	for ln in lines:
		parts = ln.split()
		if len(parts) != 5:
			raise ValueError(f"Annotation {path} should contain 5 values per line, got: {ln}")
		int(parts[0])  # ensure class id is numeric
		for val in parts[1:]:
			float(val)
	return lines


def reset_output(root: Path) -> None:
	if root.exists():
		shutil.rmtree(root)
	for sub in ("images/train", "images/val", "labels/train", "labels/val"):
		(root / sub).mkdir(parents=True, exist_ok=True)


def copy_image(src: Path, dst: Path) -> None:
	dst.parent.mkdir(parents=True, exist_ok=True)
	shutil.copy2(src, dst)


def write_label(path: Path, lines: List[str]) -> None:
	path.parent.mkdir(parents=True, exist_ok=True)
	with path.open("w", encoding="utf-8") as fh:
		if lines:
			fh.write("\n".join(lines) + "\n")


def main() -> None:
	class_names = load_class_names(LABELS_FILE)
	annotated_files = sorted(ANNOTATIONS_DIR.glob("*.txt"))

	if not annotated_files:
		raise FileNotFoundError(f"No annotation files found in {ANNOTATIONS_DIR}")
	if not RAW_IMAGES_DIR.exists():
		raise FileNotFoundError(f"Image directory not found: {RAW_IMAGES_DIR}")

	reset_output(OUTPUT_ROOT)

	annotated_basenames = set()
	train_count = 0

	for ann_path in annotated_files:
		base = ann_path.stem
		annotated_basenames.add(base)
		img_path = RAW_IMAGES_DIR / f"{base}.jpg"
		if not img_path.exists():
			raise FileNotFoundError(f"Annotated image missing: {img_path}")

		labels = parse_annotation(ann_path)
		copy_image(img_path, OUTPUT_ROOT / "images/train" / img_path.name)
		write_label(OUTPUT_ROOT / "labels/train" / f"{base}.txt", labels)
		train_count += 1

		# Also copy annotated samples into val split with the same labels
		copy_image(img_path, OUTPUT_ROOT / "images/val" / img_path.name)
		write_label(OUTPUT_ROOT / "labels/val" / f"{base}.txt", labels)

	include_unlabeled_val = os.environ.get("DATASET2_INCLUDE_UNLABELED_VAL", "0") == "1"
	val_count = train_count

	if include_unlabeled_val:
		for img_path in sorted(RAW_IMAGES_DIR.glob("*.jpg")):
			if img_path.stem in annotated_basenames:
				continue
			copy_image(img_path, OUTPUT_ROOT / "images/val" / img_path.name)
			write_label(OUTPUT_ROOT / "labels/val" / f"{img_path.stem}.txt", [])
			val_count += 1

	with DATASET_YAML.open("w", encoding="utf-8") as fh:
		fh.write("# dataset2 generated by utils/form_dataset2.py\n")
		fh.write(f"path: {OUTPUT_ROOT.as_posix()}\n")
		fh.write("train: images/train\n")
		fh.write("val: images/val\n")
		fh.write("names:\n")
		for idx, name in enumerate(class_names):
			fh.write(f"  {idx}: {name}\n")

	print(f"Prepared dataset2 at {OUTPUT_ROOT}")
	print(f"Training images: {train_count} | Validation images: {val_count}")


if __name__ == "__main__":
	main()

